POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdyIsImlkIjoxLCJpYXQiOjE2OTU3MDkzMzF9.NIM4x8AHro1zMaDDOrZ-vNN1VxOL_faWa15naqlVesg

{
    "content": "note creation using no important",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "tejfellow",
    "name": "TEJ Fellow 1"
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "pariyar",
    "password": "secret"
}
