POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdyIsImlkIjoyMSwiaWF0IjoxNjk1ODAxMzgyfQ.TGy6RNKpN8tVYb8X_Up4x1ew-ArpTEMKx03-xZwvv3k

{
    "content": "note creation using no important",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "unique",
    "name": "TEJ Fellow 1"
}
###
PUT http://localhost:3001/api/notes/899
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "tejfellow",
    "password": "secret"
}

###
GET http://localhost:3001/api/notes/8


###
GET http://localhost:3001/api/notes/
